name: jhtest
favicon: null
layout_spectrum: 0.08030733442865312
typography_spectrum: 0.9761824384331703
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.566066010389477
  lightness: 0.2455809481907636
  saturation: 0.8721157179679722
  rhythmicContrast: 0.045526228845119476
purpose: []
